---

- name: Install jenkins
  package:
    name: jenkins
    state: present
  tags:
    - jenkins
    - jenkins-install

- name: Ensure jenkins is running
  service:
    name: jenkins
    state: started
    enabled: true
  tags:
    - jenkins
    - jenkins-service
